import { Level } from "./interfaces/level";

const testLvl: Level = {
    name: "Test Level",
    description: "A test level",
    author: "Mole",
    bombs: [
        {
            type: "small",
            count: 1
        },
        {
            type: "medium",
            count: 2
        },
        {
            type: "large",
            count: 3
        }
    ],
    goals: [
        5,
        10,
        15
    ],
    tiles: [
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "target", value: 5 },
            { type: "empty" },
            { type: "empty" },
            { type: "target", value: 5 },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "target", value: 1 },
            { type: "empty" },
            { type: "empty" },
            { type: "target", value: 1 },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "target", value: 1 },
            { type: "empty" },
            { type: "empty" },
            { type: "target", value: 1 },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "target", value: 1 },
            { type: "empty" },
            { type: "empty" },
            { type: "target", value: 1 },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "target", value: 1 },
            { type: "empty" },
            { type: "empty" },
            { type: "target", value: 1 },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "target", value: 1 },
            { type: "empty" },
            { type: "empty" },
            { type: "target", value: 1 },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "target", value: 1 },
            { type: "empty" },
            { type: "empty" },
            { type: "target", value: 1 },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ],
        [
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
            { type: "empty" },
        ]
    ]
};

export { testLvl };